# Generated by Django 4.2.7 on 2024-01-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrace', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datum_konani',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='misto',
            field=models.TextField(default=''),
        ),
    ]
