# Generated by Django 4.2.7 on 2024-01-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrace', '0003_event_datum_konani_event_misto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='vytvoril',
        ),
        migrations.AlterField(
            model_name='event',
            name='datum_vytvoreni',
            field=models.DateTimeField(null=True),
        ),
    ]
