# Generated by Django 4.2.7 on 2024-01-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrace', '0004_remove_event_vytvoril_alter_event_datum_vytvoreni'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(default='https://placehold.co/600x400'),
        ),
    ]
