# Generated by Django 4.2.7 on 2024-01-24 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrace', '0005_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ucast_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='vytvoreno_uzivatelem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField(auto_now_add=True)),
                ('udalost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrace.event')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cas_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('udalost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrace.event')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
